 
 # `معالجة البيانات باستخدام مكتبة بانداز`
 
  # `Data Manipulation by Pandas`

## Section 01: Transforming DataFrames | تحويل أطر البيانات

### `1.1 Inspecting a DataFrame | فحص إطار البيانات`

In [15]:
# pandas استدعاء مكتبة
import pandas as pd
from IPython.display import display


# سحب البيانات واستعراضها على هيئة إطار بيانات
diamonds = pd.read_csv('Datasets/diamonds.csv')

# عرض إطار البيانات
display(diamonds.head())

# الحصول على معلومات إطار البيانات
print(diamonds.shape)
print(diamonds.info())

   carat        cut color clarity  depth  table  price     x     y     z
0   0.31      Ideal     G     VS1   62.4   55.0    802  4.35  4.33  2.71
1   1.50       Good     G     SI2   64.3   57.0   8190  7.29  7.20  4.66
2   0.90    Premium     H     VS2   62.8   58.0   3810  6.17  6.13  3.86
3   1.01      Ideal     F     VS2   60.9   58.0   7411  6.43  6.47  3.93
4   0.33  Very Good     D     VS1   63.2   56.0   1109  4.45  4.44  2.81

(1002, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    1002 non-null   float64
 1   cut      1002 non-null   object
 2   color    1002 non-null   object
 3   clarity  1002 non-null   object
 4   depth    1002 non-null   float64
 5   table    1002 non-null   float64
 6   price    1002 non-null   int64
 7   x        1002 non-null   float64
 8   y        1002 non-null   float64
 9   z        1002 non-null   float64
dtypes: float64(6), int64(1), object(3)
memory usage: 78.4+ KB
None

### `1.2 statistical and descriptive explanation of data | الشرح الوصفي والاحصائي للبيانات`

- carat: وزن الماسة بالقيراط ( الغرام الواحد = 5 قراريط.)
- cut: جودة القطع (مقبولة، جيدة ، جيدة جدًا ، ممتازة ، مثالية) | (Fair, Good, Very Good, Premium, Ideal)
- color: لون الماس ، من J (الأسوأ) إلى D (الأفضل)
- clarity: الوضوح قياس مدى وضوح الماس [I1 (الأسوأ) ، SI2 ، SI1 ، VS2 ، VS1 ، VVS2 ، VVS1 ، IF (الأفضل)]
- depth: النسبة المئوية للعمق الكلي = z / mean(x, y) = 2 * z / (x + y)
- table: عرض المنضدة العليا للماسة بالنسبة إلى أوسع نقطة
- price: السعر بالدولار الأمريكي.
- x: الطول بالملليمتر
- y: العرض بالملليمتر
- z: العمق بالملليمتر

In [20]:
# الشرح الاحصائي للبيانات الرقمية
display(diamonds.describe())

,carat,depth,table,price,x,y,z
count,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000
mean,0.790259,61.791018,57.437824,3830.668663,5.713583,5.712675,3.525359
std,0.466697,1.439065,2.225651,3881.895676,1.107418,1.098264,0.693850
min,0.200000,56.900000,44.000000,357.000000,3.830000,3.840000,0.000000
25%,0.400000,61.100000,56.000000,937.500000,4.690000,4.702500,2.900000
50%,0.700000,61.850000,57.000000,2385.000000,5.700000,5.710000,3.520000
75%,1.030000,62.500000,59.000000,5171.500000,6.510000,6.500000,4.017500
max,2.480000,71.800000,66.000000,18692.000000,8.870000,8.810000,5.450000

### `1.3 DataFrame Parts | أجزاء إطار البيانات`

In [53]:
# Numpy استخراج القيم على هيئة مصفوفة 
print(diamonds.values)
print(15 * '---')

# استخراج صف واحد فقط 
print(diamonds.values[0])
print(15 * '---')

# استخراج قيمة من عمود
print(diamonds.values[0][1])

[[0.31 'Ideal' 'G' ... 4.35 4.33 2.71]
 [1.5 'Good' 'G' ... 7.29 7.2 4.66]
 [0.9 'Premium' 'H' ... 6.17 6.13 3.86]
 ...
 [0.43 'Ideal' 'H' ... 4.85 4.84 3.02]
 [0.7 'Ideal' 'E' ... 5.72 5.75 3.47]
 [0.52 'Ideal' 'H' ... 5.2 5.23 3.15]]
---------------------------------------------
[0.31 'Ideal' 'G' 'VS1' 62.4 55.0 802 4.35 4.33 2.71]
---------------------------------------------
Ideal

In [55]:
# طباعة أسماء الأعمدة
print(diamonds.columns)
print(15 * "---")

# طباعة نطاق الفهرسة
print(diamonds.index)

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')
---------------------------------------------
RangeIndex(start=0, stop=1002, step=1)

### `1.4 Rows Sorting | ترتيب الصفوف`

In [59]:
#  ترتيب الصفوف وفقًا لسمة السعر بشكل تصاعدي
diamonds_price = diamonds.sort_values("price")

# عرض أول 10 صفوف
display(diamonds_price.head(10))

     carat        cut color clarity  depth  table  price     x     y     z
493   0.23  Very Good     F     VS1   60.9   57.0    357  3.96  3.99  2.42
90    0.32       Good     D      I1   64.0   54.0    361  4.33  4.36  2.78
575   0.26      Ideal     H     SI2   62.5   53.0    362  4.09  4.13  2.57
693   0.20      Ideal     E     VS2   59.7   55.0    367  3.86  3.84  2.30
982   0.23       Fair     G    VVS2   61.4   66.0    369  3.87  3.91  2.39
784   0.28       Good     G     VS2   61.8   61.0    394  4.20  4.21  2.60
133   0.23  Very Good     E     VS1   59.5   58.0    402  4.01  4.06  2.40
74    0.30       Good     G     SI1   63.2   55.0    417  4.26  4.29  2.70
861   0.26  Very Good     G     VS1   61.9   56.0    418  4.07  4.10  2.53
805   0.32  Very Good     F     SI2   62.6   56.0    421  4.37  4.41  2.75

In [60]:
#  ترتيب الصفوف وفقًا لسمة السعر بشكل تنازلي
diamonds_price = diamonds.sort_values("price", ascending = False)

# عرض أول 10 صفوف
display(diamonds_price.head(10))

     carat        cut color clarity  depth  table  price     x     y     z
664   2.48  Very Good     F     SI2   63.4   56.0  18692  8.64  8.55  5.45
289   2.40       Good     I     SI1   56.9   62.0  18541  8.87  8.81  5.03
594   1.61      Ideal     D     VS2   62.0   55.0  18318  7.51  7.50  4.67
223   2.01    Premium     H     SI1   61.4   56.0  18295  8.19  8.13  5.01
258   2.01    Premium     H     SI1   61.7   60.0  18188  8.06  7.96  4.94
691   2.39    Premium     I     VS1   61.2   60.0  17642  8.63  8.60  5.27
309   2.18  Very Good     G     SI2   61.0   60.0  17475  8.29  8.33  5.07
951   2.01    Premium     I     VS2   61.1   60.0  17433  8.06  8.12  4.94
958   1.59      Ideal     F     VS1   62.9   57.0  17366  7.38  7.48  4.62
742   1.50  Very Good     E     VS1   59.5   61.0  16988  7.43  7.46  4.43

In [79]:
#  ترتيب الصفوف وفقًا لسمتي السعر ونوع القطع  

diamonds_price_cut = diamonds.sort_values(["cut", "price"] , ascending = [True, False])
display(diamonds_price_cut)

     carat        cut color clarity  depth  table  price     x     y     z
561   2.11       Fair     I     SI1   67.2   60.0  15282  7.86  7.80  5.26
15    1.50       Fair     F     VS2   65.3   57.0  13853  7.15  7.12  4.66
120   2.29       Fair     J     VS2   57.0   66.0  13701  8.80  8.60  4.98
765   2.01       Fair     I     SI2   66.5   61.0  10671  7.81  7.75  5.17
536   1.55       Fair     H     SI2   64.6   58.0   9045  7.28  7.21  4.68
..     ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
519   0.26  Very Good     G    VVS2   62.2   56.0    426  4.08  4.10  2.54
805   0.32  Very Good     F     SI2   62.6   56.0    421  4.37  4.41  2.75
861   0.26  Very Good     G     VS1   61.9   56.0    418  4.07  4.10  2.53
133   0.23  Very Good     E     VS1   59.5   58.0    402  4.01  4.06  2.40
493   0.23  Very Good     F     VS1   60.9   57.0    357  3.96  3.99  2.42

[1002 rows x 10 columns]

### `1.5 Subsetting by columns | التجزئة من خلال الأعمدة`

In [76]:
#  التجزئة من خلال اختار عامود واحد فقط (سمة)  
cut = diamonds["cut"]

# عرض الاجتزاء
display(cut.head(7))

# فاصل
print(20 * "---")

# التجزئة من خلال اختار أكثر من عمود (عدة سمات) 
multiple_attributes = diamonds[["cut", "clarity", "color"]]

# عرض الاجتزاء 
display(multiple_attributes.head(7))

0        Ideal
1         Good
2      Premium
3        Ideal
4    Very Good
5        Ideal
6      Premium
Name: cut, dtype: object

------------------------------------------------------------

         cut clarity color
0      Ideal     VS1     G
1       Good     SI2     G
2    Premium     VS2     H
3      Ideal     VS2     F
4  Very Good     VS1     D
5      Ideal     VS1     G
6    Premium     SI1     G

### `1.6 Subsetting by rows | التجزئة من خلال الصفوف`

In [82]:
# التجزئة من خلال ترشيح قيمة نصية محددة
G_diamonds = diamonds[diamonds["color"] == "D"]

# عرض النتيجة
display(G_diamonds)

     carat        cut color clarity  depth  table  price     x     y     z
4     0.33  Very Good     D     VS1   63.2   56.0   1109  4.45  4.44  2.81
40    0.52  Very Good     D     SI1   62.7   56.0   1323  5.08  5.13  3.20
41    0.43    Premium     D     SI1   61.1   59.0   1064  4.89  4.83  2.97
43    0.71    Premium     D     SI1   60.6   58.0   2913  5.77  5.79  3.50
46    0.56  Very Good     D    VVS1   61.8   55.0   2866  5.27  5.31  3.27
..     ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
946   0.37      Ideal     D    VVS1   61.3   56.0   1764  4.60  4.63  2.83
953   1.02       Fair     D     SI1   66.4   60.0   4798  6.29  6.21  4.15
960   0.38  Very Good     D    VVS2   60.0   62.0   1200  4.70  4.73  2.83
981   1.00    Premium     D     SI1   59.6   57.0   5880  6.54  6.44  3.87
995   0.30    Premium     D     VS2   60.3   60.0    911  4.31  4.28  2.59

[109 rows x 10 columns]

In [93]:
# التجزئة من خلال ترشيح الصفوف من خلال عدة قيم نصية 

best_cut_list = ["Premium", "Ideal"]
best_cut_diamonds = diamonds[diamonds["cut"].isin(best_cut_list)]

# عرض النتيجة
display(best_cut_diamonds)

      carat      cut color clarity  depth  table  price     x     y     z
0      0.31    Ideal     G     VS1   62.4   55.0    802  4.35  4.33  2.71
2      0.90  Premium     H     VS2   62.8   58.0   3810  6.17  6.13  3.86
3      1.01    Ideal     F     VS2   60.9   58.0   7411  6.43  6.47  3.93
5      1.08    Ideal     G     VS1   62.0   55.0   6779  6.62  6.57  4.09
6      1.07  Premium     G     SI1   61.6   58.0   5453  6.60  6.56  4.05
...     ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
996    0.37    Ideal     E     VS2   62.7   56.0   1041  4.60  4.55  2.87
998    0.90    Ideal     I     SI1   61.6   55.0   3908  6.20  6.22  3.82
999    0.43    Ideal     H    VVS1   62.3   54.0   1169  4.85  4.84  3.02
1000   0.70    Ideal     E     VS2   60.5   59.0   3201  5.72  5.75  3.47
1001   0.52    Ideal     H    VVS1   60.4   57.0   1778  5.20  5.23  3.15

[658 rows x 10 columns]

In [86]:
# ترشيح إطار البيانات ليتضمن الماسات ذات العمق الكلي الأكثر من 65
dia_depth_more_65 = diamonds[(diamonds["depth"] > 65)]

# عرض النتيجة
display(dia_depth_more_65)

     carat   cut color clarity  depth  table  price     x     y     z
15    1.50  Fair     F     VS2   65.3   57.0  13853  7.15  7.12  4.66
79    1.00  Fair     H     SI2   66.5   62.0   3248  6.19  6.10  4.09
156   1.50  Fair     H     SI1   66.1   57.0   7832  7.06  6.98  4.64
157   1.50  Fair     H     SI1   66.1   57.0   7832  7.06  6.98  4.64
221   1.01  Fair     E    VVS1   66.1   55.0   8529  6.19  6.10  4.06
260   1.01  Good     E     VS2   65.6   55.0   5829  6.16  6.22  4.06
316   0.98  Fair     G     SI2   66.6   56.0   3332  6.12  6.02  4.04
407   0.50  Fair     H     VS1   66.5   60.0   1155  4.93  4.85  3.25
451   0.70  Fair     D     SI1   66.5   55.0   2339  5.51  5.47  3.65
458   0.71  Good     F     SI1   66.2   55.0   2396  5.49  5.53  3.65
539   0.96  Fair     G     SI2   66.8   61.0   2539  6.15  6.04  4.07
561   2.11  Fair     I     SI1   67.2   60.0  15282  7.86  7.80  5.26
659   1.02  Fair     H     VS1   71.8   56.0   4455  6.04  5.97  4.31
667   0.72  Fair     I    VVS2   65.7   57.0   2131  5.56  5.64  3.68
731   0.84  Good     G     SI1   65.1   55.0   2872  5.88  5.97  3.86
765   2.01  Fair     I     SI2   66.5   61.0  10671  7.81  7.75  5.17
825   0.90  Fair     F     SI2   69.0   59.0   2536  5.89  5.82  4.04
900   0.90  Fair     I     SI1   65.3   61.0   2873  5.98  5.94  3.89
953   1.02  Fair     D     SI1   66.4   60.0   4798  6.29  6.21  4.15

### `1.7 Adding new columns to DataFrame | إضافة أعمدة (سمات) جديدة لإطار البيانات`

In [98]:
# إضافة عمود جديد إلى إطار البيانات
diamonds["volume"] = diamonds["x"] * diamonds["y"] * diamonds["z"]

# عرض النتيجة
display(diamonds.head(10))

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.31,Ideal,G,VS1,62.4,55.0,802,4.35,4.33,2.71,51.044205
1,1.50,Good,G,SI2,64.3,57.0,8190,7.29,7.20,4.66,244.594080
2,0.90,Premium,H,VS2,62.8,58.0,3810,6.17,6.13,3.86,145.993306
3,1.01,Ideal,F,VS2,60.9,58.0,7411,6.43,6.47,3.93,163.496253
4,0.33,Very Good,D,VS1,63.2,56.0,1109,4.45,4.44,2.81,55.519980
5,1.08,Ideal,G,VS1,62.0,55.0,6779,6.62,6.57,4.09,177.888006
6,1.07,Premium,G,SI1,61.6,58.0,5453,6.60,6.56,4.05,175.348800
7,0.33,Premium,H,VS1,59.5,59.0,743,4.53,4.48,2.68,54.388992
8,0.44,Ideal,H,IF,62.0,57.0,1255,4.87,4.91,3.02,72.213334
9,1.00,Premium,G,VS1,58.6,61.0,6989,6.57,6.50,3.83,163.560150